{{- if or .Values.config.doveadm.user .Values.config.doveadm.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dovewarden.fullname" . }}-doveadm
  labels:
    {{- include "dovewarden.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.doveadm.user }}
  username: {{ .Values.config.doveadm.user | b64enc }}
  {{- end }}
  {{- if .Values.config.doveadm.password }}
  password: {{ .Values.config.doveadm.password | b64enc }}
  {{- end }}
{{- end }}
